# Generated by Django 2.2.4 on 2019-08-24 14:04

import django.db.models.deletion
from django.db import migrations, models

import shop_for_all.helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'active')], default='active', max_length=32)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'products'), ('model', 'product')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            bases=(shop_for_all.helpers.models.BasicModel, models.Model),
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active')], default='active', max_length=32)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='common.Price')),
            ],
        ),
    ]
