# Generated by Django 2.2.4 on 2019-08-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contentwishlist_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='codename',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
