# Generated by Django 2.2.4 on 2019-08-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190826_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentwishlist',
            options={'verbose_name': 'content wishlist', 'verbose_name_plural': 'contents wishlists'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'price', 'verbose_name_plural': 'prices'},
        ),
        migrations.AlterModelOptions(
            name='pricelog',
            options={'verbose_name': 'price log', 'verbose_name_plural': 'prices logs'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'wishlist', 'verbose_name_plural': 'wishlists'},
        ),
    ]
