# Generated by Django 2.2.4 on 2019-08-24 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop_for_all.helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20190824_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('codename', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='stores', to='products.Category')),
                ('products', models.ManyToManyField(related_name='stores', to='products.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(shop_for_all.helpers.models.BasicModel,),
        ),
    ]
