# Generated by Django 2.2.4 on 2019-08-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190824_1404'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stores', to='products.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='shops.Store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_stores', to='products.Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='shops.Store')),
            ],
        ),
    ]
