# Generated by Django 2.2.4 on 2019-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190824_1404'),
        ('shops', '0002_auto_20190824_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(related_name='stores', through='shops.StoreCategory', to='products.Category'),
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(related_name='stores', through='shops.StoreProduct', to='products.Product'),
        ),
    ]
