# Generated by Django 2.2.4 on 2019-08-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20190824_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_category', to='shops.Store'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product', to='shops.Store'),
        ),
    ]
