# Generated by Django 2.2.4 on 2019-08-24 10:36

from django.db import migrations, models
import django.db.models.deletion
import shop_for_all.helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('codename', models.SlugField(max_length=255, unique=True)),
            ],
            bases=(models.Model, shop_for_all.helpers.models.BasicModel),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('codename', models.SlugField(max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.Category')),
            ],
            bases=(models.Model, shop_for_all.helpers.models.BasicModel),
        ),
    ]
